<a href="https://colab.research.google.com/github/Code-tanisha/Data-Science-Python/blob/master/Creating_Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating NumPy Arrays

The following ways are commonly used when you know the size of the array beforehand:

np.ones(): Create array of 1s

np.zeros(): Create array of 0s

np.random.random(): Create array of random numbers

np.arange(): Create array with increments of a fixed step size

np.linspace(): Create array of fixed length

In [ ]:
import numpy as np

In [ ]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [ ]:
# creating a 1-D array of ones
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

**Notice that, by default, numpy creates data type = float64**

In [ ]:
arr.dtype

dtype('float64')

**we can provide dtype explicitly using dtype**

In [ ]:
arr = np.ones(5, dtype = int)
arr

array([1, 1, 1, 1, 1])

**Creating 5 x 3 array of ones**

In [ ]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Creating arrays of zeros**

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
# List library for crating range of 1 to 5
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
# Similar function in numpy is
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
# floating range
np.arange(5.0)

array([0., 1., 2., 3., 4.])

**Notice that 3 is included, 35 is not, as in standard python list**

from 3 to 35 step of 2

In [ ]:
np.arange(3,35,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [ ]:
# create random numpy array
np.random.randint(2, size = 10)

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 1])

In [ ]:
np.random.randint(3,4, size = 10)   # here we want integer starting from 3 and ending at 4

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

**Array 'arange' Function**

Description
Create an array of first 10 multiples of 5 using the 'arange' function.

In [ ]:

array_multipleof5 = np.arange(5,55,5)

print(array_multipleof5)

[ 5 10 15 20 25 30 35 40 45 50]


**2D Array of random numbers**

In [ ]:
# This will create a 2D numpy arrays in 3 rows , 4 columns in float
# we use numpy.random.random to create floating point random nos
np.random.random([3,4])

array([[0.21041918, 0.52097462, 0.90825339, 0.09230169],
       [0.19410434, 0.49982833, 0.28253731, 0.87750257],
       [0.08273422, 0.78417344, 0.60607308, 0.80002953]])

**Sometimes you know the length of the array and not the step size**

Array of length 20 between 1 and 10

In [ ]:
# when we use linspace 1st we give start and stop and the length and the size mentioned
# below is a 1D numpy array ot a 2D array as ther is no rows and columns

np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])