<a href="https://colab.research.google.com/github/Code-tanisha/Data-Science-Python/blob/master/MathematicalOperations_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Operations on NumPy Arrays

The learning objectives of this section are:

Manipulate arrays

    Reshape arrays

    Stack arrays

Perform operations on arrays

    Perform basic mathematical operations

    Apply built-in functions

    Apply your own functions

    Apply basic linear algebra operations


In [22]:
import numpy as np

In [23]:
# We will create 2 numpy arrays
array1 = np.array([10, 20, 30, 40, 50])
array2 =np.arange(5)
array1


array([10, 20, 30, 40, 50])

In [24]:
array2

array([0, 1, 2, 3, 4])

In [25]:
array3 = array1 + array2
array3

array([10, 21, 32, 43, 54])

In [26]:
# Example
array = np.linspace(1,10,5)
array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### Stacking Arrays

##### np.hstack() and n.vstack()

Stacking is done using the np.hstack() and np.vstack() methods. For horizontal stacking, the number of rows should be the same, while for vertical stacking, the number of columns should be the same.


In [27]:
# Note that np.hstack(a, b) throws an error - you need to pass the arrays as a list

a = np.array([1,2,3])
b = np.array([2,3,4])
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [28]:
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [29]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
# Now if we want to create a 2D aaray of shape 3 x 4
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
array1 = np.arange(12).reshape(3,4)
array2 = np.arange(20).reshape(5,4)
print(array1)
print(array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [32]:
# now if we apply vertical stack
np.vstack((array1, array2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [33]:
# From 2-D Araay it converted to 1D
p = [[1, 5],[3, 7],[4, 9]]
np.reshape(p,-1)

array([1, 5, 3, 7, 4, 9])

In [34]:
np.reshape(p, (1, -1))

array([[1, 5, 3, 7, 4, 9]])

**Stacking arrays**
Description
Merge the three arrays provided to you to form a one 4x4 array.

[Hint: Check the function np.transpose() in the 'Manipulating Arrays' notebook provided.]

Input:
Array 1: 3*3

[[7, 13, 14]

[18, 10, 17]

[11, 12, 19]]

Array 2: 1-D array

[16, 6, 1]

Array 3: 1*4 array

[[5, 8, 4, 3]]

Output:

[[7 13 14 5]

[18 10 17 8]

[11 12 19 4]

[16 6 1 3]]

In [35]:
list_1 = [[7,13,14],[18,10,17],[11,12,19]]
list_2 = [16,6,1]
list_3 = [[5,8,4,3]]

final_array = np.hstack([np.vstack([np.array(list_1),np.array(list_2)]), np.transpose(np.array(list_3))])
print(final_array)

[[ 7 13 14  5]
 [18 10 17  8]
 [11 12 19  4]
 [16  6  1  3]]


**  NUMPY BUILT IN OPERATIONS**

In [36]:
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
np.power(array1, 3)

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]])

In [38]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
x = np.array([-2,-1,0,1,2])
x

array([-2, -1,  0,  1,  2])

In [40]:
# converting every value to apsolute value
abs(x)

array([2, 1, 0, 1, 2])

In [41]:
# or
np.absolute(x)

array([2, 1, 0, 1, 2])

## **Trignomentry Functions**

In [42]:
np.pi

3.141592653589793

In [43]:
# now if we want to divide the pi ie divide 0 to 3.14 into 5 equally spaced values
theta = np.linspace(0, np.pi, 5)
theta

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [44]:
np.sin(theta)

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

In [45]:
np.cos(theta)

array([ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17, -7.07106781e-01,
       -1.00000000e+00])

#### Exponential & Logarithmic functions

In [46]:
x = [1,2,3,10]
x = np.array(x)

In [47]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 2.20264658e+04])

In [48]:
np.power(x,3)

array([   1,    8,   27, 1000])

In [49]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 2.30258509])

In [50]:
np.log2(x)

array([0.        , 1.        , 1.5849625 , 3.32192809])

In [51]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 1.        ])

**EXAMPLE**

In [52]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [53]:
# we can also create empty numpy array and the values which we gat are randomly initialized and they dont have any value
y = np.empty(5)
y

array([ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17, -7.07106781e-01,
       -1.00000000e+00])

In [54]:
y = x * 10
y

array([ 0, 10, 20, 30, 40])

In [55]:
# Another way of multiplying which meand multiplying all the values of x with 12 and storing it in y
np.multiply(x, 12, out = y)

array([ 0, 12, 24, 36, 48])

In [56]:
y = np.zeros(10)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
# here we want power of all the element and store it in y
# but this will give an erroe becoz x is of size 5 and we want to store it in a numpy array of size 10

np.power(2,x,out=y)

ValueError: ignored

In [ ]:
# but if we want to store the square of x in every other element of y then
np.power(2,x,out=y[::2])

In [ ]:
# now y is filled with x on every other element
y

### Aggregate

In [58]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [59]:
# Now if we want to sum all the falues of the numpy array
np.add.reduce(x)

15

In [60]:
# Accumulate fucntion will add the no one after the other and saving the result in the place ie. 1, 1+2, 1+2+3, ...
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [61]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

#### APPLYING BASIC LINEAR ALGEBRA OPREATIONS

numpy provides the np.linalg package to apply comman linear algebra function

np.linalg.inv : inverse if a matrix.

np.linalg.det : Determinant of a matrix.

np.linalg.eig : Eigenvalues and eigenvectiors of a matrix.

You can also multiply matrices using np.dot(a,b)


In [62]:
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [63]:
# RANK OF A MATRIX
# Rank of the ,atrix is the no of linearly independent rows and columns

np.linalg.matrix_rank(A)

3

In [64]:
# Trace of matrix is
# it is jut the sum of the elemnets of the matrix of diagonal

np.trace(A)

11

In [65]:
# Determinant of matrix A

np.linalg.det(A)

-306.0

In [70]:
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [66]:
# Inverse of matrix
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [68]:
B = np.linalg.inv(A)
B

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [69]:
# Now we want to multiply matrix A&B
# We are multiplying A and inverse of A 
np.matmul(A, B)

array([[ 1.00000000e+00,  0.00000000e+00,  2.77555756e-17],
       [-1.38777878e-17,  1.00000000e+00,  1.38777878e-17],
       [-4.16333634e-17,  1.38777878e-16,  1.00000000e+00]])